readonly package system {
     package functional_layer {
        readonly part def <'system_product'> product {
             doc Title /* Product */
        }
    }
     package requirements;
     package actors {
         actor def <'1'> '9c10137f-ad05-4f93-b9a8-06ab0539b947' {
             doc Notes /*  */
             doc Title /* Actor 1 */
             doc Description /*  */
             doc Goals /*  */
             doc Frustrations /*  */
        }
    }
}

