readonly package system {
     package functional_layer {
        readonly part def <'system_product'> product {
             doc Title /* Product */
        }
    }
     package requirements;
     package actors {
         actor def '998b6918-2639-437d-961d-43eac36c3e43' {
             doc Notes /*  */
             doc Title /* Actor 2 */
             doc Description /*  */
             doc Goals /*  */
             doc Frustrations /*  */
        }
    }
}

